# `version` is now deprecated
# https://docs.docker.com/compose/compose-file/#version-top-level-element

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/prod.Dockerfile
    restart: always
    networks:
      - my_network

  django: &django
    build:
      context: ./backend/main
      dockerfile: ./compose/production/django/Dockerfile
    image: main_production_django
    container_name: django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      - my_network

  postgres:
    build:
      context: ./backend/main
      dockerfile: ./compose/production/postgres/Dockerfile
    image: django_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - my_network

  redis:
    image: redis:6
    networks:
      - my_network

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
      - 3000:3000
      - 8000:8000
    depends_on:
      - web
      - django
    restart: always
    networks:
      - my_network


# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
